#!/bin/bash

# Define common options
PYTHON_SCRIPT="edit.py"
COMMON_ARGS="--num_steps 30 --name 'flux-dev' --offload"

# Define runs as individual strings (no line breaks inside array entries)
runs=(
"--source_prompt \"An image of parked cars. There are rain drops on view.\" --target_prompt \"An image of parked cars. There are no rain drops on view.\" --guidance 2 --inject 10 --source_img_dir /scratch/gilbreth/lwickrem/data/allweather/input/58_rain.png"
"--source_prompt \"The image shows a row of parked cars in an outdoor parking lot, taken from inside a vehicle through a rain-speckled window. Various cars—ranging in colors like white, silver, red, and gray—are neatly lined up along the right side of the road, with a cream-colored sedan prominently positioned in the foreground. Tall trees with broad, leafy canopies stretch across the top of the image, casting soft shadows and lending a tranquil, natural atmosphere to the urban setting. In the background, hints of a red-roofed building peek through the greenery. The most noticeable sign of image degradation is the heavy presence of raindrops on the glass, which distort the clarity of the scene behind them. The water droplets cause blurring, light scattering, and refraction, making parts of the cars and surroundings appear fuzzy or warped. This visual interference prevents a clean view of the environment, reducing the sharpness and detail one would expect in a high-resolution, unobstructed photograph.\" --target_prompt \"In the ground truth, fully restored version of the image, the scene appears crisp, vibrant, and unobstructed—offering a clear, undistorted view of a quiet outdoor parking lot nestled beneath a canopy of large, leafy trees. Each vehicle in the neatly aligned row of parked cars is rendered with sharp edges and visible detail, including textures on the body panels, glints of light reflecting off windows and mirrors, and easily identifiable features like grilles, headlights, and license plates. The cream-colored sedan in the foreground stands out prominently, its contours well-defined. The pavement is dry or only subtly damp, revealing fine surface textures and painted parking lines. In the background, a red-roofed building becomes fully visible through the open gaps between tree trunks and branches, adding a touch of architectural context to the serene environment. The trees overhead are lush and sharply detailed, with clearly defined branches and leaves against a soft blue sky. Overall, the restored image evokes clarity, calm, and realism, free from the visual noise introduced by raindrops or glass distortion.\" --guidance 2 --inject 10 --source_img_dir /scratch/gilbreth/lwickrem/data/allweather/input/58_rain.png"
"--source_prompt \"An image of car stopped before a white pedestrian crossing. It is snowing and the snow obscures the view. There are people on the side walk in the far background. The car is an E950 mercedes.\" --target_prompt \"An image of car stopped before a white pedestrian crossing. It is not snowing and the view is clear. There are people on the side walk in the far background. The car is an E950 mercedes.  The Image is sharp, clean and no snow effects.\" --guidance 2 --inject 10 --source_img_dir /scratch/gilbreth/lwickrem/data/allweather/input/city_read_03728.jpg"
"--source_prompt \"The image shows a dark-colored Mercedes-Benz sedan driving through a city street intersection during active snowfall. The car is captured at an angle, revealing the side and rear, with its red taillights illuminated. The setting appears to be a busy commercial district, with several pedestrians on sidewalks and storefronts in the background, including large windows showcasing warm, yellow interior lighting. Architectural detailing and signage suggest a mid-20th-century urban environment, likely in a metropolitan area like New York City. However, image degradation is present due to the falling snow, which appears prominently in the foreground as large, white flakes. These flakes partially obscure the vehicle and background details, causing visual noise and occlusion, particularly over the car’s windows, body, and the crosswalk lines. The snow also adds a sense of motion blur and visual interference, making the overall scene feel slightly grainy and cluttered, reducing the sharpness and clarity that would otherwise define the street scene.\" --target_prompt \"In the ground truth, fully restored version of the image, the scene appears clear, sharp, and free of any obstructions caused by snowfall. A sleek, dark-colored Mercedes-Benz sedan is prominently featured, its glossy finish reflecting the ambient city lights and street surroundings. The rear and side profiles of the car are distinctly visible, with crisp edges, gleaming wheels, and clearly legible details like the license plate and manufacturer emblem. The crosswalk lines on the pavement are clean and well-defined, and the road surface shows subtle texture and wet reflections, possibly from earlier precipitation. In the background, the architecture of the surrounding buildings is rendered with fine detail—storefront signs, window displays, and decorative reliefs on the façade are all easily distinguishable. Pedestrians along the sidewalks appear well-lit and sharply defined, their winter clothing adding a sense of seasonal context without visual interference. The bright, warm lights inside the shops contrast with the cool outdoor tones, creating a vibrant, bustling urban atmosphere. Overall, the restored image delivers a high-resolution, lifelike capture of a city street scene, brimming with clarity and detail.\" --guidance 2 --inject 10 --source_img_dir /scratch/gilbreth/lwickrem/data/allweather/input/city_read_03728.jpg"
)

# Output directory base
OUTPUT_BASE="/scratch/gilbreth/lwickrem/RF_Inversion/RF-Solver-Edit/FLUX_Image_Edit/results"

# Run each experiment
for i in "${!runs[@]}"; do
  echo "Running experiment $((i+1))..."
  eval python $PYTHON_SCRIPT ${runs[$i]} $COMMON_ARGS --output_dir "$OUTPUT_BASE"
done
